eval "BOARDTITLE = 'FortTree'" unless defined? BOARDTITLE
eval "BRANCHES_PER_PAGE = 10" unless defined? BRANCHES_PER_PAGE
eval "SHOWTITLETXT=true" unless defined? SHOWTITLETXT
eval "SMILEY_ASSIST=true" unless defined? SMILEY_ASSIST
eval "MAX_UPLOAD_SIZE = 5.megabytes" unless defined? MAX_UPLOAD_SIZE
eval "VALID_ATTACHMENT_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/pjpeg', 'image/tiff', 'image/x-png', 'image/bmp', 'image/svg+xml']" unless defined? VALID_ATTACHMENT_TYPES
eval "STORAGE = ENV['STORAGE']" unless defined? STORAGE
eval "S3_BUCKET = ENV['S3_BUCKET']" unless defined? S3_BUCKET
eval "S3_KEY = ENV['S3_KEY']" unless defined? S3_KEY
eval "S3_SECRET = ENV['S3_SECRET']" unless defined? S3_SECRET
eval "PHOTO_PATH = ENV['PHOTO_PATH']" unless defined? PHOTO_PATH
